/**
 * preset-archive-parity.test.ts — every shipped preset must diff clean against
 * the archived `simulation.json` it claims to reproduce.
 *
 * This is the WP8 acceptance criterion "every new preset diff-clean vs its
 * archived manifest", and it is deliberately a DIFFERENT check from
 * `validation/test/preset-batch-parity.test.ts`:
 *
 *   - the batch XML says what the run was **asked** for;
 *   - `reproducibility.parameters` says what the run **executed**.
 *
 * The whole `pushThetaThreshold` episode is a case where those two disagreed
 * (batch `-0.25`, executed `0.0`), so checking only one of them would have
 * missed it. Both are checked, and the one place they disagree is declared in
 * the preset definition (`archiveExceptions`) and explained by a ledger entry
 * (`PROVENANCE_QUIRKS#pushtheta-batch-zeroing`) rather than absorbed silently.
 *
 * ## The comparison
 *
 * An archived manifest may carry FEWER parameters than the 41 a `RunConfig`
 * always names — 11 in `present-day-three-arm/`, 33 in `phase-e/`, 40 in
 * `scenario-e/`, 41 in `scenario-e-v2/` — because a Java run only records the
 * parameters that build of `ContextCreator` knew about. The contract is
 * therefore:
 *
 *   for every parameter the archived manifest names,
 *       preset[name] === manifest[name]      (modulo declared exceptions)
 *   and no archived parameter is unknown to the schema.
 *
 * The second half matters as much as the first: an archived name the schema does
 * not have would mean the 41-parameter surface is incomplete, which is exactly
 * the WP8 question ("are the 21 E and 7 SE parameters really all there?") asked
 * of primary evidence instead of of a document.
 *
 * ## Why the values are read, never restated
 *
 * The expected values come out of `docs/runs/**\/simulation.json` at test time.
 * Transcribing them into this file would make the test assert that a human typed
 * the same numbers twice — the "expectation generated by the thing under test"
 * pattern this project has explicitly rejected.
 *
 * ## Artifact gating
 *
 * `docs/runs/` is the read-only 375 MB Java golden archive, outside `websim/`.
 * Absent (a websim-only checkout) the suite reports as SKIPPED behind a loud
 * banner, and is a hard failure on a runner that sets
 * `WEBSIM_REQUIRE_ARTIFACTS` — the shared skip-vs-fail policy, plan §5.3.
 */

import { readFileSync } from "node:fs";
import path from "node:path";

import { expect, it } from "vitest";

import {
  checkPhaseEParameterCompleteness,
  checkScenarioEParameterCompleteness,
  PROVENANCE_QUIRKS,
} from "../src/manifest.js";
import type { PresetDefinition, PresetId } from "../src/presets/index.js";
import { PRESET_DEFINITIONS, PRESETS } from "../src/presets/index.js";
import type { ParamName } from "../src/schema.js";
import {
  E_PARAM_NAMES,
  isParamName,
  PARAM_NAMES,
  repastConstantType,
  SE_PARAM_NAMES,
} from "../src/schema.js";

// The archive root contract (env override + default) lives in exactly one place;
// importing it rather than restating it means a change there cannot leave this
// suite quietly looking in the wrong directory.
import { describeArchive } from "../../pipeline/src/archive/root.js";
import { artifactGate, describeGated } from "../../tools/artifact-gate.js";

const ARCHIVE = describeArchive();

/** Every archived run directory some preset claims, de-duplicated, in order. */
const CLAIMED_RUNS: readonly string[] = [
  ...new Set(PRESET_DEFINITIONS.flatMap((d) => d.archivedManifests)),
];

const archivedPresets: readonly PresetDefinition[] = PRESET_DEFINITIONS.filter(
  (d) => d.archivedManifests.length > 0,
);

function manifestPath(runDir: string): string {
  return path.join(ARCHIVE.root, ...runDir.split("/"), "simulation.json");
}

interface ArchivedManifest {
  readonly reproducibility?: {
    readonly parameters?: Record<string, unknown>;
    readonly source_integrity?: { readonly git_working_tree_dirty?: unknown };
  };
}

/** The executed parameter block, as numbers, with the run named on failure. */
function archivedParameters(runDir: string): Record<string, number> {
  const raw = JSON.parse(readFileSync(manifestPath(runDir), "utf8")) as ArchivedManifest;
  const params = raw.reproducibility?.parameters;
  if (params === undefined) {
    throw new Error(`${runDir}/simulation.json has no reproducibility.parameters block`);
  }
  const out: Record<string, number> = {};
  for (const [name, value] of Object.entries(params)) {
    if (typeof value !== "number") {
      throw new Error(`${runDir}: parameter ${name} is ${typeof value}, not a number`);
    }
    out[name] = value;
  }
  return out;
}

const gate = artifactGate({
  gate: "shared:preset-archive-parity",
  suite: "presets vs the archived executed manifests",
  evidence:
    "every shipped preset checked parameter for parameter against the executed parameter block " +
    "of the archived run it claims to reproduce (docs/runs/phase-e, scenario-e, scenario-e-v2, " +
    "present-day-three-arm), including the single declared pushThetaThreshold exception and the " +
    "manifest-completeness gates (h) and (i)",
  artifacts: CLAIMED_RUNS.map((runDir) => ({
    source: "archive" as const,
    label: runDir,
    path: manifestPath(runDir),
  })),
});

describeGated(gate, () => {
  it("finds every archived run the presets claim", () => {
    expect(gate.satisfied, gate.report).toBe(true);
    // 12 archived presets over 18 distinct run directories: the three E0 nulls
    // each claim three archives (phase-e / scenario-e / scenario-e-v2).
    expect(CLAIMED_RUNS.length).toBe(18);
    expect(archivedPresets).toHaveLength(12);
  });

  // --- the diff-clean criterion --------------------------------------------

  for (const definition of archivedPresets) {
    for (const runDir of definition.archivedManifests) {
      it(`${definition.id} diffs clean against ${runDir}`, () => {
        const archived = archivedParameters(runDir);
        const preset = PRESETS[definition.id];
        const exceptions = new Map(definition.archiveExceptions.map((e) => [e.param, e]));

        // (1) No archived parameter may be unknown to the 41-parameter schema.
        const unknown = Object.keys(archived).filter((name) => !isParamName(name));
        expect(unknown, `${runDir} names parameters the schema lacks`).toEqual([]);

        // (2) Agreement on every parameter the manifest records, with declared
        //     exceptions compared against their archived-executed value.
        const undeclared: string[] = [];
        for (const [name, archivedValue] of Object.entries(archived)) {
          if (!isParamName(name)) {
            continue;
          }
          const exception = exceptions.get(name);
          const expected = exception === undefined ? preset[name] : exception.archivedExecutedValue;
          if (!Object.is(archivedValue, expected)) {
            undeclared.push(
              `${name}: preset ${String(preset[name])} vs archived ${String(archivedValue)}`,
            );
          }
        }
        expect(undeclared, `${definition.id} vs ${runDir}`).toEqual([]);

        // (3) Every DECLARED exception must actually be one. A stale exception
        //     would silently exempt a parameter that no longer differs, which is
        //     how an exception list rots into a blanket waiver.
        for (const e of definition.archiveExceptions) {
          expect(archived, `${runDir} does not record ${e.param}`).toHaveProperty(e.param);
          expect(preset[e.param], `${definition.id}.${e.param} preset value`).toBe(e.presetValue);
          expect(archived[e.param], `${runDir}.${e.param} archived value`).toBe(
            e.archivedExecutedValue,
          );
          expect(e.presetValue, `${e.param} is declared an exception but does not differ`).not.toBe(
            e.archivedExecutedValue,
          );
        }
      });
    }
  }

  it("finds exactly one archive exception in the whole shipped set", () => {
    // Stated as a census rather than per-preset so a sixth preset quietly
    // acquiring an exception shows up as a failure here, not as a passing test.
    const all = archivedPresets.flatMap((d) =>
      d.archiveExceptions.map((e) => `${d.id}:${e.param}`),
    );
    expect(all.sort()).toEqual([
      "SE2_worst_plausible_E18_d1:pushThetaThreshold",
      "SE2_worst_plausible_E18_d2:pushThetaThreshold",
      "SE_severe_v1_E18:pushThetaThreshold",
      "SE_severe_v1_E19:pushThetaThreshold",
    ]);
    const params = new Set(
      archivedPresets.flatMap((d) => d.archiveExceptions.map((e) => e.param)),
    );
    expect([...params]).toEqual(["pushThetaThreshold"]);
  });

  it("keeps the E0 nulls exception-free across all three archives", () => {
    // The nulls are the family that must be reproducible with no caveat at all:
    // they are the R3 vehicle. An exception appearing here would mean the R3
    // proof is being run against a configuration the archive did not execute.
    for (const id of ["E0_null_A", "E0_null_B", "E0_null_C"] as const) {
      const definition = PRESET_DEFINITIONS.find((d) => d.id === id);
      expect(definition?.archiveExceptions, `${id} must have no archive exception`).toEqual([]);
      expect(definition?.archivedManifests).toHaveLength(3);
    }
  });

  // --- the comparison must be able to fail ---------------------------------

  it("reports a perturbed preset value as a diff (mutation check)", () => {
    // A diff-clean assertion that cannot go red proves nothing. Perturb one
    // parameter of the loaded config and confirm the same comparison rejects it.
    const runDir = "scenario-e-v2/SE2-E18-d1-seed42";
    const archived = archivedParameters(runDir);
    const tampered = { ...PRESETS.SE2_worst_plausible_E18_d1, closureDraw: 3 };
    const diffs = Object.entries(archived).filter(
      ([name, value]) =>
        isParamName(name) &&
        name !== "pushThetaThreshold" &&
        !Object.is(value, tampered[name as ParamName]),
    );
    expect(diffs.map(([name]) => name)).toEqual(["closureDraw"]);
  });

  // --- manifest completeness gates (h) and (i) ------------------------------

  it("satisfies gate (h) — all 21 Phase-E parameters — for every shipped preset", () => {
    for (const id of Object.keys(PRESETS) as PresetId[]) {
      const result = checkPhaseEParameterCompleteness(Object.keys(PRESETS[id]));
      expect(result.missing, `${id} missing Phase-E parameters`).toEqual([]);
      expect(result.ok).toBe(true);
    }
  });

  it("satisfies gate (i) — 7 Scenario-E parameters + closureDraw at code 3", () => {
    for (const id of Object.keys(PRESETS) as PresetId[]) {
      const config = PRESETS[id];
      const result = checkScenarioEParameterCompleteness(
        Object.keys(config),
        config.closuresCode,
      );
      expect(result.missing, `${id} missing Scenario-E parameters`).toEqual([]);
      expect(result.ok).toBe(true);
    }
    // The conditional half really is conditional, and really does fire.
    const worst = PRESETS.SE2_worst_plausible_E18_d1;
    expect(worst.closuresCode).toBe(3);
    const withoutDraw = Object.keys(worst).filter((n) => n !== "closureDraw");
    expect(checkScenarioEParameterCompleteness(withoutDraw, 3).missing).toEqual(["closureDraw"]);
    expect(checkScenarioEParameterCompleteness(withoutDraw, 1).missing).toEqual([]);
  });

  it("confirms gate (h) holds on the archived manifests it was written for", () => {
    // Cross-check in the other direction: the gate implementation is run against
    // the primary evidence (WP8-SPEC-archive-gates.md §3.3 records "21/21 present
    // in every run"). If the port's E_PARAM_NAMES were wrong, this fails even
    // though the preset-side check above would still pass.
    for (const runDir of CLAIMED_RUNS) {
      const names = Object.keys(archivedParameters(runDir));
      const isPreE = runDir.startsWith("present-day-three-arm/");
      const result = checkPhaseEParameterCompleteness(names);
      if (isPreE) {
        // The pre-E three-arm runs predate the decision layer: 11 parameters,
        // none of them Phase-E. Asserted rather than skipped, so the gate is
        // shown able to fail on real data.
        expect(names).toHaveLength(11);
        expect(result.missing).toHaveLength(E_PARAM_NAMES.length);
      } else {
        expect(result.missing, `${runDir} is missing Phase-E parameters`).toEqual([]);
      }
    }
  });

  it("confirms gate (i) holds on the Scenario-E archives and fails on the pre-SE ones", () => {
    for (const runDir of CLAIMED_RUNS) {
      const archived = archivedParameters(runDir);
      const names = Object.keys(archived);
      const code = archived["closuresCode"] ?? 0;
      const result = checkScenarioEParameterCompleteness(names, code);
      const hasSeBlock = runDir.startsWith("scenario-e");
      if (hasSeBlock) {
        expect(result.missing, `${runDir} is missing Scenario-E parameters`).toEqual([]);
      } else {
        // phase-e/ (33 parameters) and present-day-three-arm/ (11) predate the
        // Scenario-E block entirely, which is why gate (i) is `--se` runs only.
        expect(result.missing).toHaveLength(SE_PARAM_NAMES.length);
      }
    }
  });

  it("reproduces the archived per-archive parameter counts", () => {
    // WP8-SPEC-archive-gates.md §1.8 / §3.3: 11 (pre-E), 33 (phase-e),
    // 40 (scenario-e, 33 + the 7 SE params), 41 (scenario-e-v2, + closureDraw).
    const counts = new Map<string, number>();
    for (const runDir of CLAIMED_RUNS) {
      const archive = runDir.split("/")[0] as string;
      const n = Object.keys(archivedParameters(runDir)).length;
      const seen = counts.get(archive);
      expect(seen === undefined || seen === n, `${archive} has mixed parameter counts`).toBe(true);
      counts.set(archive, n);
    }
    expect(Object.fromEntries(counts)).toEqual({
      "present-day-three-arm": 11,
      "phase-e": 33,
      "scenario-e": 40,
      "scenario-e-v2": 41,
    });
    expect(PARAM_NAMES).toHaveLength(41);
  });

  // --- the honesty note is attached where it is needed ----------------------

  it("attaches the pushThetaThreshold ledger note to every preset that needs it", () => {
    const quirk = PROVENANCE_QUIRKS.find((q) => q.id === "pushtheta-batch-zeroing");
    expect(quirk, "the provenance ledger has no pushtheta-batch-zeroing entry").toBeDefined();
    for (const definition of PRESET_DEFINITIONS) {
      const needsNote = definition.archiveExceptions.some(
        (e) => e.param === "pushThetaThreshold",
      );
      expect(
        definition.quirkNotes.includes("pushtheta-batch-zeroing"),
        `${definition.id}: quirkNotes and archiveExceptions disagree`,
      ).toBe(needsNote);
      for (const e of definition.archiveExceptions) {
        expect(
          PROVENANCE_QUIRKS.map((q) => q.id),
          `${definition.id}.${e.param} cites an unknown ledger entry`,
        ).toContain(e.quirkNote);
      }
      for (const id of definition.quirkNotes) {
        expect(PROVENANCE_QUIRKS.map((q) => q.id)).toContain(id);
      }
    }
    // The ledger's own numbers must match the archive it describes.
    expect(quirk?.archivedExecutedValue).toBe(0);
    expect(quirk?.presetValue).toBe(-0.25);
    expect(archivedParameters("scenario-e/SE-E18-seed42")["pushThetaThreshold"]).toBe(0);
    expect(archivedParameters("scenario-e-v2/SE2-E18-d1-seed42")["pushThetaThreshold"]).toBe(0);
    // ... and the E0 nulls record the CODE FALLBACK, not the zeroed value,
    // because their batch files omit the Scenario-E block entirely (§1.8).
    expect(archivedParameters("scenario-e-v2/E0null-A-seed42")["pushThetaThreshold"]).toBe(-0.25);
  });

  // --- the never-regress gotcha, checked against the instrument's own files --

  it("keeps every negative archived value typed 'double', never 'number'", () => {
    // Gotcha 4: Repast's batch loader zeroes negative constant_type="number"
    // constants. The manifests record what EXECUTED, so this is the standing
    // audit on the other side: for every negative value the archive executed,
    // the port's batch-typing rule must say "double".
    const negatives = new Set<string>();
    for (const runDir of CLAIMED_RUNS) {
      for (const [name, value] of Object.entries(archivedParameters(runDir))) {
        if (value < 0 && isParamName(name)) {
          negatives.add(name);
          expect(repastConstantType(name, value), `${runDir}: ${name}=${value}`).not.toBe("number");
        }
      }
    }
    // The precondition is real, not hypothetical: the archive really does
    // execute negative values, and they really are among the 28 WP8 parameters.
    expect([...negatives].sort()).toEqual(["alphaHazard", "pushThetaThreshold"]);
    for (const name of negatives) {
      expect(
        [...E_PARAM_NAMES, ...SE_PARAM_NAMES] as readonly string[],
        `${name} is negative but outside the 21 E + 7 SE surface`,
      ).toContain(name);
    }
  });
});
