package websim.exporter.decision;

import java.io.File;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;

import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.GeometryFactory;

import geography.agents.ELayerSampler;
import geography.agents.GisAgent;
import geography.agents.PopulationSampler;
import geography.agents.Shelter;
import geography.data.CsvLoader;
import geography.env.SmokeField;
import geography.routing.StreetNetwork;

import repast.simphony.context.Context;
import repast.simphony.context.DefaultContext;
import repast.simphony.engine.environment.RunEnvironment;
import repast.simphony.engine.environment.RunState;
import repast.simphony.engine.schedule.Schedule;
import repast.simphony.engine.schedule.ScheduleParameters;
import repast.simphony.parameter.DefaultParameters;
import repast.simphony.space.gis.DefaultGeography;
import repast.simphony.space.gis.Geography;

import websim.exporter.world.CertifiedGraph;
import websim.exporter.world.Io;

/**
 * WP8 — the <b>decision-layer trace oracle</b>.
 *
 * <p>Stands up a real headless Repast runtime (a live {@link DefaultContext}, a
 * {@link Geography} projection literally named {@code "Geography"}, a
 * {@link Schedule}, a {@link RunEnvironment} parameter map and a {@link RunState}
 * master context), builds the full 6,842-resident world at the archived Phase-E
 * configurations, and steps the <b>certified</b> {@code GisAgent.step()} through
 * it, dumping every decision-layer quantity in raw IEEE-754 hex.
 *
 * <p><b>No model arithmetic is re-implemented here.</b> {@code StreetNetwork}
 * owns the graph, the snapping, the trees and the closure blocking;
 * {@code CsvLoader} owns every parse; {@code Shelter} owns capacity, reserve and
 * the open window; {@code SmokeField} owns the hourly array;
 * {@code PopulationSampler} and {@code ELayerSampler} own every build-time draw
 * and the seed derivations; {@code GisAgent} owns the whole decision layer; and
 * {@code ContextCreator$ClosureWave} owns the wave. The three step-local
 * quantities that reflection cannot reach — the hazard {@code u} and {@code p}
 * and the L1 per-candidate utility {@code v} — are read out of the certified
 * frame that computed them, through the insertion-only source probe generated by
 * {@link Instrument} (see the class doc there, and the audit file it writes).
 *
 * <p><b>What IS mirrored, and why it is safe.</b> {@code ContextCreator.build()}
 * cannot be invoked headlessly (it needs a {@code Geography.rs} scenario
 * directory, a parameter schema and a live {@code RunState} before it starts), so
 * three of its loops are mirrored statement for statement exactly as
 * {@code WorldFixtures} and {@code MovementTrace} already mirror them, with the
 * display-only side effects dropped: the shelter loop (L546-L591), the closure
 * schedule (L639-L707) and the resident placement + Phase-E second pass
 * (L710-L790). None of those loops contains a line of decision-layer arithmetic;
 * the whole of it lives in {@code GisAgent}, which is invoked, not copied. The
 * mirror is held honest by the graph census assertion, by the archived realised
 * marginals, and by the two-JVM neutrality gate.
 *
 * <p><b>Agent order is index order, not Repast's RANDOM_PRIORITY shuffle.</b>
 * Stated, not hidden. Every quantity this oracle exists to pin — {@code z_R}, the
 * hour bucket, {@code u}, {@code p}, the draw sequence, {@code awareTick},
 * {@code thetaScaled}, {@code barrierCost}, the belief set — is provably
 * order-independent: each depends only on the resident's own private stream, its
 * own attributes, and {@code anyShelterOpen(context, tick)}, which is
 * {@code static} and resident-independent. What order does change is who wins the
 * last bed, and that is already the port's single declared divergence channel
 * ({@code sim.ts:16-23}). A TypeScript run with {@code agentOrder: "identity"}
 * reproduces this dump's ordering exactly.
 */
public final class DecisionTrace {

	private DecisionTrace() { }

	// ---------------------------------------------------------- constants

	private static final int NUM_AGENTS = 6842;
	private static final double MINUTES_PER_TICK = 1.0;
	private static final double TICKS_PER_HOUR = 60.0 / MINUTES_PER_TICK;
	private static final double WALKING_SPEED_MPS = 1.30;
	private static final double EVACUATION_THRESHOLD_UGM3 = 55.5;
	private static final double SHELTER_ARRIVAL_DISTANCE_M = 200.0;

	/** THE SAMPLING RULE, half 2 — see {@link DecisionProbe#inCohort}. */
	private static final int EARLY_HOURS = 12;
	private static final int COHORT_MOD = 64;

	/** Hard stop so a mis-sized sampling rule cannot fill the disk. */
	private static final long ROW_BUDGET = 40_000_000L;

	// -------------------------------------------------------------- config

	private static final class Cfg {
		final String id;
		final int scenarioCode;
		final int simulationHours;
		final double triageReserveFraction;
		final int respectShelterOpeningDates = 1;
		final int enableHeterogeneity = 1;
		final double pAwareInit;
		final double pHeavy;
		final double pPet;
		final double pDependents;
		final double groupSpeedDeltaMps;
		final int shelterPolicyVariant;
		final int smokeSeriesCode;
		final double smokeScale = 1.0;
		final int closuresCode;
		final int closureDraw;
		final int enableDecisionLayer;
		/**
		 * Seeds this config is run at. The five ARCHIVED Phase-E configs run at all
		 * three archived seeds; the three coverage extensions run at seed 42 only,
		 * because their job is to make an otherwise-dead branch executable once, not
		 * to characterise seed variation, and the ~500 MB disk budget is real.
		 */
		int[] seeds = SEEDS;
		// DecisionConfig, in the certified constructor's positional order
		final int informationRegime;
		final int enableHazardDeparture;
		final double alphaHazard;
		final double bRisk;
		final double wOfficial;
		final double gammaVuln;
		final double sigmaTheta;
		final double riskHalfLifeH;
		final double lambdaOutreachPerDay;
		final double barrierBelongings;
		final double barrierPet;
		final double barrierDependents;
		final int petPolicyDefault;
		final double betaTravelTime;
		final double betaCapacityPrior;
		final double pushThetaThreshold;
		final double kPush;
		final double pStuck;
		final double stuckDelayH;

		String sheltersCsv;
		String scenarioName;

		Cfg(String id, int scenarioCode, int simulationHours, double triageReserveFraction,
				double pAwareInit, double groupSpeedDeltaMps, int shelterPolicyVariant,
				int smokeSeriesCode, int closuresCode, int closureDraw, int informationRegime,
				int enableHazardDeparture, double gammaVuln, double sigmaTheta, double barrier,
				int petPolicyDefault, double betaCapacityPrior, double pushThetaThreshold,
				double kPush, double pStuck, double stuckDelayH, int enableDecisionLayer,
				double lambdaOutreachPerDay) {
			this.enableDecisionLayer = enableDecisionLayer;
			this.lambdaOutreachPerDay = lambdaOutreachPerDay;
			this.id = id;
			this.scenarioCode = scenarioCode;
			this.simulationHours = simulationHours;
			this.triageReserveFraction = triageReserveFraction;
			this.pAwareInit = pAwareInit;
			this.pHeavy = 0.284;
			this.pPet = 0.117;
			this.pDependents = 0.0044;
			this.groupSpeedDeltaMps = groupSpeedDeltaMps;
			this.shelterPolicyVariant = shelterPolicyVariant;
			this.smokeSeriesCode = smokeSeriesCode;
			this.closuresCode = closuresCode;
			this.closureDraw = closureDraw;
			this.informationRegime = informationRegime;
			this.enableHazardDeparture = enableHazardDeparture;
			this.alphaHazard = -8.0;
			this.bRisk = 0.4;
			this.wOfficial = 1.1;
			this.gammaVuln = gammaVuln;
			this.sigmaTheta = sigmaTheta;
			this.riskHalfLifeH = 48.0;
			this.barrierBelongings = barrier;
			this.barrierPet = barrier;
			this.barrierDependents = barrier;
			this.petPolicyDefault = petPolicyDefault;
			this.betaTravelTime = 1.0;
			this.betaCapacityPrior = betaCapacityPrior;
			this.pushThetaThreshold = pushThetaThreshold;
			this.kPush = kPush;
			this.pStuck = pStuck;
			this.stuckDelayH = stuckDelayH;
		}
	}

	/**
	 * The archived Phase-E configurations, transcribed from
	 * {@code Geography/batch/batch_params_2026_*.xml}.
	 *
	 * <p><b>Closure configs run LAST and only once.</b> {@code blockEdge} and
	 * {@code declareClosureSchedule} mutate the shared {@code StreetNetwork}
	 * permanently, so a closure arm must never precede a non-closure arm inside one
	 * JVM. The order below is enforced by an assertion in {@link #main}.
	 *
	 * <p><b>{@code pushThetaThreshold} is 0.0, not -0.25.</b> The archived SE batch
	 * files declare it {@code constant_type="number"}, and Repast's batch reader
	 * zeroes negative {@code "number"} constants. 0.0 is therefore what the archive
	 * EXECUTED, and an oracle must reproduce what ran, not what was intended
	 * (never-regress gotcha 4 / WP8-SPEC-decision.md QUIRK 23).
	 */
	private static List<Cfg> configs() {
		List<Cfg> c = new ArrayList<Cfg>();
		//                 id       scen hrs  reserve pAware  gDelta pol smoke clo draw regime haz gamma sigma barrier pet betaCap pushThr kPush pStuck delayH layer lambda
		c.add(new Cfg("E0-A",    0, 312, 0.0, 1.0,   0.0,   0,  0,   0,  1,   0,   0,  0.0,  0.0,  0.0,   1,  0.0,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		c.add(new Cfg("E0-B",    1, 312, 0.0, 1.0,   0.0,   0,  0,   0,  1,   0,   0,  0.0,  0.0,  0.0,   1,  0.0,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		c.add(new Cfg("E0-C",    2, 312, 0.0, 1.0,   0.0,   0,  0,   0,  1,   0,   0,  0.0,  0.0,  0.0,   1,  0.0,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		c.add(new Cfg("ER-A",    0, 312, 0.0, 0.356, 0.06,  1,  0,   0,  1,   1,   1,  0.25, 1.0,  0.26,  0,  0.2,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		c.add(new Cfg("ER-C",    2, 312, 0.0, 0.356, 0.06,  1,  0,   0,  1,   1,   1,  0.25, 1.0,  0.26,  0,  0.2,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		// ---- coverage extensions beyond the requested set --------------------
		// LEG-A: the SAME arm A with the layer OFF. Two jobs. (a) it is the only
		// configuration that can reach latch site B (GisAgent.java:440-446), the
		// layer-off twin of site A. (b) its outcome census beside E0-A's IS the R3
		// null identity, measured inside this oracle rather than asserted.
		c.add(new Cfg("LEG-A",   0, 312, 0.0, 1.0,   0.0,   0,  0,   0,  1,   0,   0,  0.0,  0.0,  0.0,   1,  0.0,   0.0,   1.0,  0.3,  3.0,  0,  0.0));
		// ERL-A: ER-A with outreach switched ON. SYNTHETIC -- no archived arm sets
		// lambdaOutreachPerDay > 0 (QUIRK 28), so D1, the UNAWARE->PRE_EVAC
		// conversion and the two-draw agent-tick are unreachable from the archive.
		// This config exists ONLY to exercise them; it is not a claim about 2020.
		c.add(new Cfg("ERL-A",   0, 312, 0.0, 0.356, 0.06,  1,  0,   0,  1,   1,   1,  0.25, 1.0,  0.26,  0,  0.2,   0.0,   1.0,  0.3,  3.0,  1,  1.0));
		// L0P-A: arm A, layer ON, regime L0, latch departure, everyone aware -- but
		// with the _elayer shelter policy file and petPolicyDefault=0 (refuse). The
		// only configuration that can reach the L0 belief path: L0 records ONLY
		// policy refusals (GisAgent.java:571-576), and no archived L0 arm has a
		// policy that refuses anybody, so `excludedByBelief` is dead everywhere else.
		c.add(new Cfg("L0P-A",   0, 312, 0.0, 1.0,   0.0,   1,  0,   0,  1,   0,   0,  0.0,  0.0,  0.0,   0,  0.0,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		// SE-E18: the ONLY way to reach the Scenario-E branches (closure scan /
		// push rule / D3 stuck draw / reroute). MUST stay last: blockEdge() and
		// declareClosureSchedule() mutate the shared StreetNetwork permanently.
		c.add(new Cfg("SE-E18",  18, 455, 0.0, 0.356, 0.06, 1,  1,   1,  1,   1,   1,  0.25, 1.0,  0.26,  0,  0.2,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		// SEC-A: the closure-branch vehicle. SE-E18 is archive-faithful but at ER
		// departure rates only ~1.5 residents are mid-walk on any given tick, so its
		// single wave at hour 79 caught nobody and reactToClosureWave never ran.
		// SEC-A fixes that on purpose: latch departure with everyone aware puts the
		// whole population on the street at once, L1 keeps refused residents
		// re-walking (no retry cap), and the worst-family schedule fires three waves.
		// It runs in its OWN JVM (see dump-decision-trace.ps1) because blockEdge()
		// mutates the shared StreetNetwork and SE-E18 must see a pristine graph.
		c.add(new Cfg("SEC-A",   0, 312, 0.0, 1.0,   0.06,  1,  0,   3,  1,   1,   0,  0.25, 1.0,  0.26,  0,  0.2,   0.0,   1.0,  0.3,  3.0,  1,  0.0));
		for (Cfg x : c) {
			if ("LEG-A".equals(x.id) || "ERL-A".equals(x.id) || "L0P-A".equals(x.id)
					|| "SEC-A".equals(x.id) || "SE-E18".equals(x.id)) {
				x.seeds = SEED42;
			}
		}
		return c;
	}

	private static final int[] SEEDS = { 42, 43, 44 };
	private static final int[] SEED42 = { 42 };

	// ------------------------------------------------- certified constants

	private static Class<?> CC;
	private static Method M_TICK_FOR_DATE;
	private static LocalDateTime SIM_START;
	private static String ENCAMPMENTS_CSV;
	private static String SMOKE_CSV;
	private static String SMOKE_SEVERE_CSV;
	private static String SMOKE_SEVERE_V2_CSV;
	private static String SHELTERS_CSV_2020;
	private static String SHELTERS_A_CSV;
	private static String SHELTERS_B_CSV;
	private static String SHELTERS_C_CSV;
	private static String CLOSURES_BASE_CSV;
	private static String CLOSURES_EXTREME_CSV;
	private static String CLOSURES_WORST_PREFIX;
	private static String CLOSURES_WORST_SUFFIX;

	private static Field F_ZR;
	private static Field F_LAST_HOUR;
	private static Field F_BELIEVED;
	private static Field F_STUCK_UNTIL;
	private static Field F_SEEN_VERSION;
	private static Field F_CURRENT_NODE;
	private static Field F_PATH_INDEX;
	private static Field F_DECISION_RNG;
	private static Field F_PUSHED;

	private static void loadCertified() throws Exception {
		CC = Class.forName("geography.agents.ContextCreator");
		M_TICK_FOR_DATE = CC.getDeclaredMethod("tickForDate", String.class, double.class,
				double.class, int.class);
		M_TICK_FOR_DATE.setAccessible(true);
		SIM_START = (LocalDateTime) sf("SIM_START");
		ENCAMPMENTS_CSV = (String) sf("ENCAMPMENTS_CSV");
		SMOKE_CSV = (String) sf("SMOKE_CSV");
		SMOKE_SEVERE_CSV = (String) sf("SMOKE_SEVERE_CSV");
		SMOKE_SEVERE_V2_CSV = (String) sf("SMOKE_SEVERE_V2_CSV");
		SHELTERS_CSV_2020 = (String) sf("SHELTERS_CSV");
		SHELTERS_A_CSV = (String) sf("SHELTERS_A_CSV");
		SHELTERS_B_CSV = (String) sf("SHELTERS_B_CSV");
		SHELTERS_C_CSV = (String) sf("SHELTERS_C_CSV");
		CLOSURES_BASE_CSV = (String) sf("CLOSURES_BASE_CSV");
		CLOSURES_EXTREME_CSV = (String) sf("CLOSURES_EXTREME_CSV");
		CLOSURES_WORST_PREFIX = (String) sf("CLOSURES_WORST_PREFIX");
		CLOSURES_WORST_SUFFIX = (String) sf("CLOSURES_WORST_SUFFIX");

		F_ZR = af("zR");
		F_LAST_HOUR = af("lastDecisionHour");
		F_BELIEVED = af("believedFull");
		F_STUCK_UNTIL = af("stuckUntilTick");
		F_SEEN_VERSION = af("seenClosureVersion");
		F_CURRENT_NODE = af("currentNodeId");
		F_PATH_INDEX = af("pathIndex");
		F_DECISION_RNG = af("decisionRng");
		F_PUSHED = af("pushedBlockages");
	}

	private static Object sf(String name) throws Exception {
		Field f = CC.getDeclaredField(name);
		f.setAccessible(true);
		return f.get(null);
	}

	private static Field af(String name) throws Exception {
		Field f = GisAgent.class.getDeclaredField(name);
		f.setAccessible(true);
		return f;
	}

	private static double dbl(Field f, Object o) {
		try {
			return f.getDouble(o);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private static int integer(Field f, Object o) {
		try {
			return f.getInt(o);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private static long lng(Field f, Object o) {
		try {
			return f.getLong(o);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private static Object obj(Field f, Object o) {
		try {
			return f.get(o);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private static double tickForDate(String iso, double fallback, int dayOffset) {
		try {
			return ((Double) M_TICK_FOR_DATE.invoke(null, iso, Double.valueOf(TICKS_PER_HOUR),
					Double.valueOf(fallback), Integer.valueOf(dayOffset))).doubleValue();
		} catch (Exception e) {
			throw new RuntimeException("certified tickForDate failed for '" + iso + "'", e);
		}
	}

	private static String resolveShelters(Cfg c) throws Exception {
		String csv;
		String name;
		switch (c.scenarioCode) {
			case 1: csv = SHELTERS_B_CSV; name = (String) sf("SCENARIO_B_NAME"); break;
			case 2: csv = SHELTERS_C_CSV; name = (String) sf("SCENARIO_C_NAME"); break;
			case 3: csv = SHELTERS_CSV_2020; name = (String) sf("HISTORICAL_REFERENCE_NAME"); break;
			case 7: csv = SHELTERS_B_CSV; name = (String) sf("SCENARIO_D_NAME"); break;
			case 18: csv = SHELTERS_A_CSV; name = (String) sf("SCENARIO_E18_NAME"); break;
			case 19: csv = SHELTERS_C_CSV; name = (String) sf("SCENARIO_E19_NAME"); break;
			case 20: csv = SHELTERS_B_CSV; name = (String) sf("SCENARIO_E20_NAME"); break;
			default: csv = SHELTERS_A_CSV; name = (String) sf("SCENARIO_A_NAME"); break;
		}
		if (c.shelterPolicyVariant == 1) {
			String variant = csv.substring(0, csv.length() - 4) + "_elayer.csv";
			if (!new File(variant).exists()) {
				throw new IllegalStateException("shelterPolicyVariant=1 but " + variant + " missing");
			}
			csv = variant;
		}
		c.scenarioName = name;
		return csv;
	}

	private static String smokeCsvFor(int code) {
		return code == 2 ? SMOKE_SEVERE_V2_CSV : code == 1 ? SMOKE_SEVERE_CSV : SMOKE_CSV;
	}

	private static String closuresCsvFor(int code, int draw) {
		if (code == 0) {
			return null;
		}
		return code == 3 ? CLOSURES_WORST_PREFIX + draw + CLOSURES_WORST_SUFFIX
				: code == 2 ? CLOSURES_EXTREME_CSV : CLOSURES_BASE_CSV;
	}

	// ------------------------------------------------------------- driver

	/** One scheduled action per tick; steps residents in creation-index order. */
	public static final class Driver {
		private final List<GisAgent> agents;
		private final RecordingRandom[] rngs;

		Driver(List<GisAgent> agents, RecordingRandom[] rngs) {
			this.agents = agents;
			this.rngs = rngs;
		}

		/** Invoked by the Repast schedule; must stay public for the scheduler. */
		public void tick() {
			for (int i = 0; i < agents.size(); i++) {
				DecisionProbe.beginAgent(i, agents.get(i), rngs[i]);
				agents.get(i).step();
			}
			DecisionProbe.endAgent();
		}
	}

	// --------------------------------------------------------------- sinks

	private static Dump.Sink[] sinks;

	private static final class SinkEmitter implements DecisionProbe.Emitter {
		public void row(int stream, String line) {
			sinks[stream].line(line);
		}
	}

	// ---------------------------------------------------------------- main

	public static void main(String[] args) throws Exception {
		File outRoot = new File(args.length > 0 ? args[0] : "out/decision-fixtures");
		String only = args.length > 1 ? args[1] : "";
		String label = args.length > 2 ? args[2] : "instrumented";
		boolean probeEnabled = !"certified".equals(label);

		loadCertified();
		Dump.Manifest man = new Dump.Manifest(outRoot);

		System.out.println("[WP8] building the certified graph ...");
		CertifiedGraph g = CertifiedGraph.build();
		Io.Manifest bridge = new Io.Manifest(outRoot);
		g.assertProductionCensus(bridge);
		man.check("graph.census", true, "nodes=" + g.report.finalGraphNodes + " undirectedEdges="
				+ g.network.streetEdgeCount() + " components=" + g.report.componentCount);

		// ---- camp table (mirror of ContextCreator L710-L723) -----------------
		List<Map<String, String>> campRows = CsvLoader.read(ENCAMPMENTS_CSV);
		List<Coordinate> campCoords = new ArrayList<Coordinate>();
		List<String> campIds = new ArrayList<String>();
		for (Map<String, String> r : campRows) {
			try {
				campCoords.add(new Coordinate(Double.parseDouble(r.get("lon")),
						Double.parseDouble(r.get("lat"))));
				campIds.add(r.get("inc_id"));
			} catch (Exception ignore) {
				/* mirror: malformed rows are silently skipped */
			}
		}
		final int nCamps = campCoords.size();
		long[] campNode = new long[nCamps];
		for (int i = 0; i < nCamps; i++) {
			campNode[i] = g.network.nearestNode(campCoords.get(i));
		}
		man.check("camps.count", nCamps == 3400, nCamps + " parseable camps of " + campRows.size());

		Map<Integer, SmokeField> smokeByCode = new LinkedHashMap<Integer, SmokeField>();
		Map<Long, StreetNetwork.ShortestPathTree> treeCache =
				new LinkedHashMap<Long, StreetNetwork.ShortestPathTree>();

		// ---- sinks ------------------------------------------------------------
		sinks = new Dump.Sink[DecisionProbe.STREAM_COUNT];
		sinks[DecisionProbe.S_HOUR] = man.sink("hour", "hour.tsv");
		sinks[DecisionProbe.S_DRAW] = man.sink("draws", "draws.tsv");
		sinks[DecisionProbe.S_TRANSITION] = man.sink("transitions", "transitions.tsv");
		sinks[DecisionProbe.S_CHOICE] = man.sink("choice", "choice.tsv");
		sinks[DecisionProbe.S_DOOR] = man.sink("door", "door.tsv");
		sinks[DecisionProbe.S_CLOSURE] = man.sink("closure", "closure.tsv");
		sinks[DecisionProbe.S_ARM] = man.sink("arm", "arm.tsv");
		Dump.Sink finalSink = man.sink("agentsFinal", "agents-final.tsv");
		Dump.Sink drawDigest = man.sink("drawDigest", "draws-digest.tsv");
		Dump.Sink shelterSink = man.sink("shelters", "shelters.tsv");
		Dump.Sink coverage = man.sink("coverage", "coverage.tsv");

		header(sinks[DecisionProbe.S_HOUR],
				"per-agent per-HOUR decision rows. kind 'b' = hour bucket, 'zr' = risk update, "
				+ "'hz' = logistic hazard.");
		sinks[DecisionProbe.S_HOUR].line("# config\tseed\tagent\t<kind-specific>  "
				+ "-- b: hour tick lastDecisionHour state cNow_hex zR_hex"
				+ " | zr: 'zr' hour cNow_hex decay_hex zR_hex"
				+ " | hz: 'hz' hour tick open vulnerable bRiskEff_hex zR_hex thetaScaled_hex"
				+ " barrierCost_hex u_hex p_hex");
		header(sinks[DecisionProbe.S_DRAW],
				"every nextDouble() consumed on a COHORT agent's private decision stream, in order");
		sinks[DecisionProbe.S_DRAW].line("# config\tseed\tagent\tdraw_index\tsite\traw_bits_hex");
		header(sinks[DecisionProbe.S_TRANSITION], "every state transition, every agent");
		sinks[DecisionProbe.S_TRANSITION].line("# config\tseed\tagent\ttick\tfrom\tto\tcause\tdetail");
		header(sinks[DecisionProbe.S_CHOICE], "chooser rows for COHORT agents; every pick for all");
		sinks[DecisionProbe.S_CHOICE].line("# config\tseed\tagent\ttick\tkind\t<kind-specific>");
		header(sinks[DecisionProbe.S_DOOR], "every door arrival and refusal, every agent");
		sinks[DecisionProbe.S_DOOR].line("# config\tseed\tagent\ttick\t<arrival|refused>\t...");
		header(sinks[DecisionProbe.S_CLOSURE], "Scenario-E closure reaction rows, every agent");
		sinks[DecisionProbe.S_CLOSURE].line("# config\tseed\tagent\ttick\tkind\t...");
		header(sinks[DecisionProbe.S_ARM], "setDecisionLayer output: the armed per-agent constants");
		sinks[DecisionProbe.S_ARM].line("# config\tseed\tagent\taware_initial\theavy_belongings"
				+ "\thas_pet\thas_dependents\ttheta_z_hex\tgroup_speed_delta_hex\tdecision_seed"
				+ "\ttheta_scaled_hex\tbarrier_cost_hex\tstate\taware_tick_hex");

		header(finalSink, "end-of-run per-agent state; the neutrality-gate artefact");
		finalSink.line("# config\tseed\tagent\tenc_id\tstart_node\tstate\taware_tick_hex"
				+ "\tevac_tick_hex\tarrival_tick_hex\ttarget_shelter\tdist_m_hex\tplanned_m_hex"
				+ "\tsnap_gap_m_hex\tnet_dist_m_hex\texposure_hex\tvwe_hex\ttravel_exposure_hex"
				+ "\thours_above_hex\tdose_hex\tair_vol_hex\tpeak_hex\toutdoor_h_hex\tretargets"
				+ "\tblockages\tpush_throughs\treroutes\tstuck_events\ttheta_scaled_hex"
				+ "\tbarrier_cost_hex\tzR_hex\tlast_decision_hour\tbelieved_full_size"
				+ "\tstuck_until_hex\tseen_closure_version\tcurrent_node\tpath_index"
				+ "\tpushed_blockages\tdraw_count");
		header(drawDigest, "per-agent draw COUNT and rolling SHA-256 over the raw bits, ALL agents "
				+ "(WP8 section 17.2: the only artefact that catches QUIRK 1)");
		drawDigest.line("# config\tseed\tagent\tdecision_seed\tdraw_count\tdraw_sha256");
		header(shelterSink, "shelter table AND the context iteration order the L0 tie-break sees");
		shelterSink.line("# config\tseed\tload_idx\titer_idx\tshelter_id\tcapacity\toperating"
				+ "\topen_tick_hex\tclose_tick_hex\treserved\tpet_intake\tadults_only\tgraph_node"
				+ "\tfinal_occupancy\tpeak_occupancy\trefused\tpolicy_refused");
		header(coverage, "branch coverage: one column per run, one row per branch of "
				+ "WP8-SPEC-decision.md");

		StringBuilder runJson = new StringBuilder();
		runJson.append("  \"samplingRule\": {\n");
		runJson.append("    \"statement\": \"A per-agent per-HOUR row is written iff COHORT(i) OR "
				+ "hour < earlyHours. A per-DRAW row is written iff COHORT(i). Chooser candidate "
				+ "rows are written iff COHORT(i); every chooser PICK, every state TRANSITION, "
				+ "every DOOR event, every CLOSURE event, every ARM row and every end-of-run row "
				+ "is written for EVERY agent, unconditionally.\",\n");
		runJson.append("    \"cohort\": \"COHORT(i) := ((i * 2654435761) mod 2^32) mod ")
				.append(COHORT_MOD).append(" == 0, i = resident creation index (0-based)\",\n");
		runJson.append("    \"earlyHours\": ").append(EARLY_HOURS).append(",\n");
		runJson.append("    \"cohortMod\": ").append(COHORT_MOD).append(",\n");
		runJson.append("    \"agentOrder\": \"identity (creation index), NOT Repast RANDOM_PRIORITY"
				+ " -- reproduce with agentOrder: 'identity'\"\n");
		runJson.append("  },\n");
		runJson.append("  \"runs\": [\n");

		List<Cfg> cfgs = configs();
		boolean seenClosureCfg = false;
		int runCount = 0;
		List<long[]> coverageCols = new ArrayList<long[]>();
		List<String> coverageNames = new ArrayList<String>();

		for (Cfg c : cfgs) {
			if (!only.isEmpty() && !only.contains(c.id)) {
				continue;
			}
			if (c.closuresCode != 0) {
				seenClosureCfg = true;
			} else if (seenClosureCfg) {
				throw new IllegalStateException("config order violates the closure-last rule: "
						+ c.id + " has no closures but a closure arm already mutated the network");
			}
			c.sheltersCsv = resolveShelters(c);
			SmokeField sf = smokeByCode.get(Integer.valueOf(c.smokeSeriesCode));
			if (sf == null) {
				sf = new SmokeField(smokeCsvFor(c.smokeSeriesCode), "Multnomah", SIM_START,
						c.smokeScale);
				smokeByCode.put(Integer.valueOf(c.smokeSeriesCode), sf);
			}
			int endHours = Math.min(c.simulationHours, sf.hours());
			int endTick = (int) (endHours * TICKS_PER_HOUR);

			for (int seed : c.seeds) {
				long t0 = System.currentTimeMillis();
				String prefix = c.id + "\t" + seed + "\t";
				DecisionProbe.resetCounts();
				DecisionProbe.configure(new SinkEmitter(), prefix, EARLY_HOURS, COHORT_MOD,
						ROW_BUDGET);
				DecisionProbe.enabled = probeEnabled;

				Run run = build(g, c, seed, sf, campCoords, campIds, campNode, treeCache);
				for (int t = 1; t <= endTick; t++) {
					run.schedule.execute();
					double now = run.schedule.getTickCount();
					if (now != t) {
						throw new IllegalStateException("schedule tick " + now + " != " + t);
					}
				}
				DecisionProbe.enabled = false;

				dumpRun(c, seed, prefix, run, finalSink, drawDigest, shelterSink);
				long picks = DecisionProbe.count(DecisionProbe.BR_ROUTENODES_ON)
						+ DecisionProbe.count(DecisionProbe.BR_ROUTENODES_OFF);
				DecisionProbe.setCount(DecisionProbe.BR_V11_STALE,
						picks - DecisionProbe.count(DecisionProbe.BR_V11_FIRST));

				long[] col = new long[DecisionProbe.BRANCHES.length];
				for (int b = 0; b < col.length; b++) {
					col[b] = DecisionProbe.count(b);
				}
				coverageCols.add(col);
				coverageNames.add(c.id + "-seed" + seed);
				runCount++;

				int sheltered = 0;
				int refused = 0;
				int unreachable = 0;
				int unaware = 0;
				int preEvac = 0;
				int enRoute = 0;
				for (GisAgent a : run.agents) {
					String s = a.getState().name();
					if ("SHELTERED".equals(s)) {
						sheltered++;
					} else if ("REFUSED_ALL_FULL".equals(s)) {
						refused++;
					} else if ("UNREACHABLE".equals(s)) {
						unreachable++;
					} else if ("UNAWARE".equals(s)) {
						unaware++;
					} else if ("PRE_EVAC".equals(s)) {
						preEvac++;
					} else {
						enRoute++;
					}
				}
				long totalDraws = 0;
				for (RecordingRandom rr : run.rngs) {
					if (rr != null) {
						totalDraws += rr.drawCount();
					}
				}
				String census = "sheltered=" + sheltered + " refused=" + refused + " unreachable="
						+ unreachable + " unaware=" + unaware + " preEvac=" + preEvac + " enRoute="
						+ enRoute + " draws=" + totalDraws;
				man.check("run." + c.id + ".seed" + seed, true, census + " ("
						+ (System.currentTimeMillis() - t0) / 1000 + " s)");
				runJson.append(runCount == 1 ? "" : ",\n");
				runJson.append("    {\"config\": \"").append(c.id).append("\", \"seed\": ")
						.append(seed).append(", \"scenarioCode\": ").append(c.scenarioCode)
						.append(", \"scenarioName\": \"").append(Dump.esc(c.scenarioName))
						.append("\", \"sheltersCsv\": \"").append(c.sheltersCsv)
						.append("\", \"smokeCsv\": \"").append(smokeCsvFor(c.smokeSeriesCode))
						.append("\", \"closuresCsv\": ")
						.append(closuresCsvFor(c.closuresCode, c.closureDraw) == null ? "null"
								: "\"" + closuresCsvFor(c.closuresCode, c.closureDraw) + "\"")
						.append(", \"simulationHours\": ").append(c.simulationHours)
						.append(", \"endHours\": ").append(endHours)
						.append(", \"endTick\": ").append(endTick)
						.append(", \"informationRegime\": ").append(c.informationRegime)
						.append(", \"enableHazardDeparture\": ").append(c.enableHazardDeparture)
						.append(", \"pAwareInit\": ").append(c.pAwareInit)
						.append(", \"sigmaTheta\": ").append(c.sigmaTheta)
						.append(", \"gammaVuln\": ").append(c.gammaVuln)
						.append(", \"barrier\": ").append(c.barrierBelongings)
						.append(", \"petPolicyDefault\": ").append(c.petPolicyDefault)
						.append(", \"betaCapacityPrior\": ").append(c.betaCapacityPrior)
						.append(", \"pushThetaThresholdExecuted\": ").append(c.pushThetaThreshold)
						.append(", \"sheltered\": ").append(sheltered)
						.append(", \"refusedAllFull\": ").append(refused)
						.append(", \"unreachable\": ").append(unreachable)
						.append(", \"unaware\": ").append(unaware)
						.append(", \"decisionDraws\": ").append(totalDraws).append("}");
				System.out.println("[WP8] " + c.id + "-seed" + seed + ": " + census);
			}
		}
		runJson.append("\n  ],\n");

		// ---- coverage table ---------------------------------------------------
		StringBuilder hdr = new StringBuilder("branch");
		for (String n : coverageNames) {
			hdr.append('\t').append(n);
		}
		hdr.append("\tTOTAL");
		coverage.line(hdr.toString());
		int uncovered = 0;
		StringBuilder uncoveredList = new StringBuilder();
		for (int b = 0; b < DecisionProbe.BRANCHES.length; b++) {
			StringBuilder row = new StringBuilder(DecisionProbe.BRANCHES[b]);
			long total = 0;
			for (long[] col : coverageCols) {
				row.append('\t').append(col[b]);
				total += col[b];
			}
			row.append('\t').append(total);
			coverage.line(row.toString());
			if (total == 0) {
				uncovered++;
				uncoveredList.append(uncoveredList.length() == 0 ? "" : "; ")
						.append(DecisionProbe.BRANCHES[b]);
			}
		}
		coverage.close();
		// Reported, never fatal: coverage of the closure branches is only complete
		// across the union of the two JVMs this dumper is run in (the closure arm
		// mutates the shared StreetNetwork permanently, so SEC-A gets its own
		// process). A per-process "all branches" assertion would therefore be false
		// by construction in both processes. The table is the report; the union is
		// taken in docs/DR-WP8-decision-oracle.md.
		boolean coverageComplete = man.check("coverage.allBranchesHit", uncovered == 0,
				uncovered == 0 ? DecisionProbe.BRANCHES.length + " branches, all covered"
						: uncovered + " of " + DecisionProbe.BRANCHES.length
								+ " NOT triggered IN THIS PROCESS: " + uncoveredList);

		for (Dump.Sink s : sinks) {
			s.close();
		}
		finalSink.close();
		drawDigest.close();
		shelterSink.close();

		man.check("rows.budgetNotTripped", !DecisionProbe.budgetTripped(),
				DecisionProbe.rowsWritten() + " probe rows written (budget " + ROW_BUDGET + ")");
		man.check("size.underBudget", man.totalBytes() < 500L * 1024 * 1024,
				(man.totalBytes() / (1024 * 1024)) + " MiB on disk");

		StringBuilder extra = new StringBuilder();
		extra.append("  \"task\": \"WP8 -- Java decision-layer trace oracle\",\n");
		extra.append("  \"label\": \"").append(Dump.esc(label)).append("\",\n");
		extra.append("  \"probeEnabled\": ").append(probeEnabled).append(",\n");
		extra.append("  \"seeds\": \"archived configs at 42/43/44; coverage extensions "
				+ "(LEG-A, ERL-A, SE-E18) at 42 only\",\n");
		extra.append("  \"numAgents\": ").append(NUM_AGENTS).append(",\n");
		extra.append("  \"minutesPerTick\": ").append(MINUTES_PER_TICK).append(",\n");
		extra.append("  \"walkingSpeedMps\": ").append(WALKING_SPEED_MPS).append(",\n");
		extra.append("  \"evacuationThresholdUgM3\": ").append(EVACUATION_THRESHOLD_UGM3)
				.append(",\n");
		extra.append("  \"simStart\": \"").append(SIM_START).append("\",\n");
		extra.append("  \"uncoveredBranches\": ").append(uncovered).append(",\n");
		extra.append(runJson);
		man.write(new File(outRoot, "manifest.json"), extra.toString());

		System.out.println("[WP8] dumps -> " + outRoot.getPath() + " (" + man.entries().size()
				+ " files, " + (man.totalBytes() / (1024 * 1024)) + " MiB)");
		int hardFailures = man.failures() - (coverageComplete ? 0 : 1);
		if (hardFailures > 0) {
			System.out.println("[WP8] " + hardFailures + " SELF-CHECK FAILURE(S)");
			System.exit(2);
		}
		System.out.println(coverageComplete
				? "[WP8] all self-checks green"
				: "[WP8] all self-checks green except per-process branch coverage "
						+ "(" + uncovered + " branches; see coverage.tsv and the DR for the union)");
	}

	private static void header(Dump.Sink s, String what) {
		s.line("# WP8 decision-layer trace oracle -- " + what);
		s.line("# produced by websim.exporter.decision.DecisionTrace from the CERTIFIED "
				+ "geography.agents.GisAgent.step(); no decision arithmetic is re-implemented");
		s.line("# doubles are the %016x of Double.doubleToRawLongBits; minutesPerTick="
				+ MINUTES_PER_TICK + "; agent order = creation index (NOT the Repast shuffle)");
	}

	// ----------------------------------------------------------- one world

	private static final class Run {
		Context<Object> context;
		Geography<Object> geography;
		Schedule schedule;
		List<GisAgent> agents;
		List<Shelter> shelters;
		RecordingRandom[] rngs;
		ELayerSampler.DecisionAttributes[] das;
	}

	private static Run build(CertifiedGraph g, Cfg c, int seed, SmokeField smoke,
			List<Coordinate> campCoords, List<String> campIds, long[] campNode,
			Map<Long, StreetNetwork.ShortestPathTree> treeCache) throws Exception {
		Run w = new Run();
		w.schedule = new Schedule();
		DefaultParameters params = new DefaultParameters();
		params.addParameter("minutesPerTick", "minutesPerTick", Double.class,
				Double.valueOf(MINUTES_PER_TICK), false);
		params.addParameter("walkingSpeedMps", "walkingSpeedMps", Double.class,
				Double.valueOf(WALKING_SPEED_MPS), false);
		params.addParameter("evacuationThresholdUgM3", "evacuationThresholdUgM3", Double.class,
				Double.valueOf(EVACUATION_THRESHOLD_UGM3), false);
		params.addParameter("shelterArrivalDistanceM", "shelterArrivalDistanceM", Double.class,
				Double.valueOf(SHELTER_ARRIVAL_DISTANCE_M), false);
		RunEnvironment.init(w.schedule, null, params, true);

		w.context = new DefaultContext<Object>("DecisionTrace");
		DefaultGeography<Object> geo = new DefaultGeography<Object>("Geography");
		w.context.addProjection(geo);
		w.geography = geo;
		RunState.init();
		RunState.getInstance().setMasterContext(w.context);

		GeometryFactory fac = new GeometryFactory();

		// ---- shelters: mirror of ContextCreator.build() L546-L591 -------------
		w.shelters = new ArrayList<Shelter>();
		for (Map<String, String> r : CsvLoader.read(c.sheltersCsv)) {
			String capStr = r.get("capacity");
			Integer capacity = (capStr == null || capStr.isEmpty()) ? null : Integer.valueOf(capStr);
			boolean operating = "operating".equalsIgnoreCase(r.get("status"));
			double lon = Double.parseDouble(r.get("lon"));
			double lat = Double.parseDouble(r.get("lat"));
			Shelter shelter = new Shelter(r.get("shelter_id"), r.get("name"), capacity, operating,
					lon, lat);
			if (c.respectShelterOpeningDates == 1) {
				shelter.setOpenWindowTicks(
						tickForDate(r.get("opened"), Double.NEGATIVE_INFINITY, 0),
						tickForDate(r.get("closed"), Double.POSITIVE_INFINITY, 1));
			}
			if (capacity != null && c.triageReserveFraction > 0.0) {
				shelter.setReservedForPriority(
						(int) Math.floor(capacity.intValue() * c.triageReserveFraction));
			}
			String petCol = r.get("pet_intake");
			if (petCol != null && !petCol.trim().isEmpty()) {
				shelter.setPetIntake(Boolean.valueOf("admit".equalsIgnoreCase(petCol.trim())));
			}
			String adultsCol = r.get("adults_only");
			if (adultsCol != null && !adultsCol.trim().isEmpty()) {
				String v = adultsCol.trim();
				shelter.setAdultsOnly("1".equals(v) || "true".equalsIgnoreCase(v)
						|| "yes".equalsIgnoreCase(v));
			}
			w.context.add(shelter);
			Coordinate co = new Coordinate(lon, lat);
			w.geography.move(shelter, fac.createPoint(co));
			long nodeId = g.network.nearestNode(co);
			shelter.setGraphNodeId(nodeId);
			Long key = Long.valueOf(nodeId);
			StreetNetwork.ShortestPathTree tree = treeCache.get(key);
			if (tree == null) {
				tree = g.network.computeTree(nodeId);
				treeCache.put(key, tree);
			}
			shelter.setRouteTree(tree);
			w.shelters.add(shelter);
		}

		// ---- closures: mirror of ContextCreator.build() L639-L707 -------------
		String closuresCsv = closuresCsvFor(c.closuresCode, c.closureDraw);
		if (closuresCsv != null) {
			g.network.declareClosureSchedule();
			TreeMap<Integer, List<long[]>> waves = new TreeMap<Integer, List<long[]>>();
			for (Map<String, String> r : CsvLoader.read(closuresCsv)) {
				long a = Long.parseLong(r.get("node_a").trim());
				long b = Long.parseLong(r.get("node_b").trim());
				int hour = Integer.parseInt(r.get("activation_hour").trim());
				List<long[]> wave = waves.get(Integer.valueOf(hour));
				if (wave == null) {
					wave = new ArrayList<long[]>();
					waves.put(Integer.valueOf(hour), wave);
				}
				wave.add(new long[] { a, b });
			}
			Class<?> waveClass = Class.forName("geography.agents.ContextCreator$ClosureWave");
			Constructor<?> ctor = waveClass.getDeclaredConstructors()[0];
			ctor.setAccessible(true);
			for (Map.Entry<Integer, List<long[]>> e : waves.entrySet()) {
				int hour = e.getKey().intValue();
				Object wave = ctor.newInstance(g.network, w.shelters, e.getValue(),
						Integer.valueOf(hour));
				w.schedule.schedule(ScheduleParameters.createOneTime(hour * TICKS_PER_HOUR,
						ScheduleParameters.FIRST_PRIORITY), wave, "apply");
			}
			System.out.println("[WP8] " + closuresCsv + ": " + waves.size() + " wave(s) scheduled");
		}

		// ---- residents: mirror of ContextCreator.build() L724-L755 ------------
		Class<?> rh = Class.forName("repast.simphony.random.RandomHelper");
		rh.getMethod("init").invoke(null);
		rh.getMethod("setSeed", int.class).invoke(null, Integer.valueOf(seed));
		Method nextIntFromTo = rh.getMethod("nextIntFromTo", int.class, int.class);

		PopulationSampler sampler = c.enableHeterogeneity == 1 ? new PopulationSampler(seed) : null;
		w.agents = new ArrayList<GisAgent>(NUM_AGENTS);
		for (int i = 0; i < NUM_AGENTS; i++) {
			int idx = ((Integer) nextIntFromTo.invoke(null, Integer.valueOf(0),
					Integer.valueOf(nCamps(campCoords) - 1))).intValue();
			Coordinate coord = campCoords.get(idx);
			GisAgent agent = new GisAgent("Site " + i, g.network, campNode[idx], campIds.get(idx),
					smoke);
			agent.setStartCoord(coord.x, coord.y);
			if (sampler != null) {
				agent.setAttributes(sampler.sample());
			}
			w.context.add(agent);
			w.geography.move(agent, fac.createPoint(coord));
			w.agents.add(agent);
		}

		// ---- Phase-E second pass: mirror of ContextCreator.build() L776-L790 --
		w.rngs = new RecordingRandom[NUM_AGENTS];
		w.das = new ELayerSampler.DecisionAttributes[NUM_AGENTS];
		if (c.enableDecisionLayer != 1) {
			// Layer OFF: ContextCreator's step 11 does not run at all, so no agent
			// carries decisionConfig/decisionAttributes and step() executes the
			// pre-E path statement for statement.
			w.schedule.schedule(ScheduleParameters.createRepeating(1, 1),
					new Driver(w.agents, w.rngs), "tick");
			return w;
		}
		ELayerSampler eSampler = new ELayerSampler(seed, c.pAwareInit, c.pHeavy, c.pPet,
				c.pDependents, c.groupSpeedDeltaMps);
		GisAgent.DecisionConfig dc = new GisAgent.DecisionConfig(c.informationRegime,
				c.enableHazardDeparture, c.alphaHazard, c.bRisk, c.wOfficial, c.gammaVuln,
				c.sigmaTheta, c.riskHalfLifeH, c.lambdaOutreachPerDay, c.barrierBelongings,
				c.barrierPet, c.barrierDependents, c.petPolicyDefault == 1, c.betaTravelTime,
				c.betaCapacityPrior, c.pushThetaThreshold, c.kPush, c.pStuck, c.stuckDelayH);
		for (int i = 0; i < NUM_AGENTS; i++) {
			GisAgent a = w.agents.get(i);
			ELayerSampler.DecisionAttributes da = eSampler.sample();
			w.das[i] = da;
			DecisionProbe.beginAgent(i, a, null);
			a.setDecisionLayer(dc, da);
			DecisionProbe.endAgent();
			// Swap the certified java.util.Random for the recording SUBCLASS of it,
			// at draw 0, seeded identically: the sequence is bit-for-bit the one the
			// untraced agent would have consumed (RecordingRandom delegates to
			// super.nextDouble()).
			RecordingRandom rr = new RecordingRandom(da.decisionSeed);
			java.util.Random orig = (java.util.Random) obj(F_DECISION_RNG, a);
			if (orig == null) {
				throw new IllegalStateException("agent " + i + " has no decisionRng after arming");
			}
			F_DECISION_RNG.set(a, rr);
			w.rngs[i] = rr;
		}

		w.schedule.schedule(ScheduleParameters.createRepeating(1, 1),
				new Driver(w.agents, w.rngs), "tick");
		return w;
	}

	private static int nCamps(List<Coordinate> campCoords) {
		return campCoords.size();
	}

	// ------------------------------------------------------ end-of-run dump

	private static void dumpRun(Cfg c, int seed, String prefix, Run w, Dump.Sink finalSink,
			Dump.Sink drawDigest, Dump.Sink shelterSink) {
		for (int i = 0; i < w.agents.size(); i++) {
			GisAgent a = w.agents.get(i);
			Shelter target = a.getTargetShelter();
			Object believed = obj(F_BELIEVED, a);
			Object pushed = obj(F_PUSHED, a);
			finalSink.line(prefix + i + "\t" + a.getEncampmentId() + "\t" + a.getStartNodeId()
					+ "\t" + a.getState().name()
					+ "\t" + DecisionProbe.hx(a.getAwareTick())
					+ "\t" + DecisionProbe.hx(a.getEvacuationTick())
					+ "\t" + DecisionProbe.hx(a.getArrivalTick())
					+ "\t" + (target == null ? "" : target.getId())
					+ "\t" + DecisionProbe.hx(a.getDistanceTraveledM())
					+ "\t" + DecisionProbe.hx(a.getPlannedRouteM())
					+ "\t" + DecisionProbe.hx(a.getSnapGapM())
					+ "\t" + DecisionProbe.hx(a.getNetworkDistToShelterM())
					+ "\t" + DecisionProbe.hx(a.getExposureUgM3h())
					+ "\t" + DecisionProbe.hx(a.getVweUgM3h())
					+ "\t" + DecisionProbe.hx(a.getExposureWhileTravelingUgM3h())
					+ "\t" + DecisionProbe.hx(a.getHoursAboveUnhealthy())
					+ "\t" + DecisionProbe.hx(a.getInhaledDoseUg())
					+ "\t" + DecisionProbe.hx(a.getAirVolumeBreathedM3())
					+ "\t" + DecisionProbe.hx(a.getPeakConcUgM3())
					+ "\t" + DecisionProbe.hx(a.getOutdoorHours())
					+ "\t" + a.getRetargetCount()
					+ "\t" + a.getBlockagesEncountered()
					+ "\t" + a.getPushThroughs()
					+ "\t" + a.getReroutes()
					+ "\t" + a.getStuckEvents()
					+ "\t" + DecisionProbe.hx(a.getThetaScaled())
					+ "\t" + DecisionProbe.hx(a.getBarrierCost())
					+ "\t" + DecisionProbe.hx(dbl(F_ZR, a))
					+ "\t" + integer(F_LAST_HOUR, a)
					+ "\t" + (believed == null ? -1 : ((java.util.Set<?>) believed).size())
					+ "\t" + DecisionProbe.hx(dbl(F_STUCK_UNTIL, a))
					+ "\t" + integer(F_SEEN_VERSION, a)
					+ "\t" + lng(F_CURRENT_NODE, a)
					+ "\t" + integer(F_PATH_INDEX, a)
					+ "\t" + (pushed == null ? -1 : ((java.util.Set<?>) pushed).size())
					+ "\t" + (w.rngs[i] == null ? -1 : w.rngs[i].drawCount()));
			if (w.rngs[i] != null) {
				drawDigest.line(prefix + i + "\t" + w.das[i].decisionSeed + "\t"
						+ w.rngs[i].drawCount() + "\t" + w.rngs[i].digestHex());
			}
		}

		// Context iteration order is what the L0 tie-break (strict <) actually
		// sees, so it is recorded rather than assumed to be load order.
		Map<String, Integer> iterOrder = new LinkedHashMap<String, Integer>();
		int k = 0;
		for (Object o : w.context.getObjects(Shelter.class)) {
			iterOrder.put(((Shelter) o).getId(), Integer.valueOf(k++));
		}
		for (int i = 0; i < w.shelters.size(); i++) {
			Shelter s = w.shelters.get(i);
			Integer it = iterOrder.get(s.getId());
			shelterSink.line(prefix + i + "\t" + (it == null ? -1 : it.intValue()) + "\t"
					+ s.getId() + "\t" + (s.getCapacity() == null ? "" : s.getCapacity().toString())
					+ "\t" + (s.isOperating() ? 1 : 0)
					+ "\t" + DecisionProbe.hx(s.getOpenTick())
					+ "\t" + DecisionProbe.hx(s.getCloseTick())
					+ "\t" + s.getReservedForPriority()
					+ "\t" + (s.getPetIntake() == null ? "unrecorded"
							: (s.getPetIntake().booleanValue() ? "admit" : "refuse"))
					+ "\t" + (s.isAdultsOnly() ? 1 : 0)
					+ "\t" + s.getGraphNodeId()
					+ "\t" + s.getOccupancy() + "\t" + s.getPeakOccupancy()
					+ "\t" + s.getRefusedCount() + "\t" + s.getPolicyRefusedCount());
		}
		System.out.println(String.format(Locale.ROOT, "[WP8] %s-seed%d dumped", c.id, seed));
	}
}
