#!/usr/bin/env python3
"""Round-5 Phase D inputs: bed-equivalence sweep CSVs + batch params.

D2 — bed-equivalence sweep. Arm B's 36 REAL locations with system capacity
scaled to s x demand for s in {0.8, 1.2, 1.4, 1.6} (B itself is s = 1.0,
already on disk). Same source file (arm A's real inventory) and the same
largest-remainder apportionment build_scenario_bc_2026.py used for B, so the
sweep points and B differ only in the capacity target. Reads where B crosses
C's access -> the exchange rate, in beds, of re-placing vs adding capacity.

D1 — window arms. A/B/C at simulationHours 24 and 72 (seeds 42-44): the
dose-decomposition of C's benefit by exposure window. Zero code change - the
params files simply set simulationHours. The episode-aligned (hour-79) arm
requires shifting SIM_START and is deliberately NOT built tonight; see
12-PHASE-D-PREDICTIONS.md for the descope note.

Scenario codes 11-14 map to the sweep CSVs in ContextCreator.
"""
import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "Geography/data/shelters/shelters_2026_current_placement.csv"
BATCH = ROOT / "Geography/batch"
DEMAND = 6842  # 2025 PIT unsheltered count; FINAL_DATA_VALIDATION_REPORT.md Task 2

SWEEP = {  # scale -> (file suffix, scenarioCode)
    0.8: ("s080", 11),
    1.2: ("s120", 12),
    1.4: ("s140", 13),
    1.6: ("s160", 14),
}
SEEDS = (42, 43, 44)
WINDOW_ARMS = {"A": 0, "B": 1, "C": 2}
WINDOW_HOURS = (24, 72)

PARAMS_TEMPLATE = """<?xml version="1.0"?>
<!-- {comment}
     Round-5 Phase D ({phase}). Generated by scripts/build_phaseD_2026.py.
     All non-listed behaviour identical to the 2026 three-arm experiment
     (n=6842, heterogeneity on, real opening dates). -->
<sweep runs="1">
\t<parameter name="numAgents" type="constant" constant_type="int" value="6842"/>
\t<parameter name="randomSeed" type="constant" constant_type="int" value="{seed}"/>
\t<parameter name="minutesPerTick" type="constant" constant_type="number" value="1.0"/>
\t<parameter name="walkingSpeedMps" type="constant" constant_type="number" value="1.30"/>
\t<parameter name="shelterArrivalDistanceM" type="constant" constant_type="number" value="200.0"/>
\t<parameter name="evacuationThresholdUgM3" type="constant" constant_type="number" value="55.5"/>
\t<parameter name="simulationHours" type="constant" constant_type="int" value="{hours}"/>
\t<parameter name="scenarioCode" type="constant" constant_type="int" value="{code}"/>
\t<parameter name="enableHeterogeneity" type="constant" constant_type="int" value="1"/>
\t<parameter name="respectShelterOpeningDates" type="constant" constant_type="int" value="1"/>
</sweep>
"""


def largest_remainder(caps, target):
    """Exactly the apportionment build_scenario_bc_2026.py uses for B."""
    total = sum(caps)
    factor = target / total
    exact = [c * factor for c in caps]
    new = [int(x) for x in exact]
    leftover = target - sum(new)
    order = sorted(range(len(caps)), key=lambda i: -(exact[i] - new[i]))
    for i in order[:leftover]:
        new[i] += 1
    assert sum(new) == target, (sum(new), target)
    return new, factor


def build_sweep_csvs():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8-sig")))
    cols = list(rows[0].keys())
    caps = [int(r["capacity"]) for r in rows]
    for scale, (suffix, code) in sorted(SWEEP.items()):
        target = round(DEMAND * scale)
        new, factor = largest_remainder(caps, target)
        out = ROOT / f"Geography/data/shelters/shelters_2026_bsweep_{suffix}.csv"
        outrows = []
        for r, old, cap in zip(rows, caps, new):
            r2 = dict(r)
            r2["capacity"] = str(cap)
            r2["capacity_basis"] = (
                f"BED_SWEEP_{suffix}_capacity_{old}x{factor:.4f}"
                f"_target_{target}_real_location_unchanged")
            outrows.append(r2)
        with open(out, "w", encoding="utf-8", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=cols)
            w.writeheader()
            w.writerows(outrows)
        print(f"{out.name}: {len(outrows)} sites, total {sum(new)} "
              f"(= {scale} x {DEMAND} = {target}), scenarioCode {code}")


def write_params(path, comment, phase, seed, hours, code):
    path.write_text(PARAMS_TEMPLATE.format(
        comment=comment, phase=phase, seed=seed, hours=hours, code=code),
        encoding="utf-8")


def build_params():
    n = 0
    for scale, (suffix, code) in sorted(SWEEP.items()):
        for seed in SEEDS:
            p = BATCH / f"batch_params_2026_BS{suffix[1:]}_seed{seed}.xml"
            write_params(p, f"BED-EQUIVALENCE SWEEP {scale}x demand at arm B's "
                            f"real locations, seed {seed}",
                         "D2 bed-equivalence sweep", seed, 312, code)
            n += 1
    for arm, code in WINDOW_ARMS.items():
        for hours in WINDOW_HOURS:
            for seed in SEEDS:
                p = BATCH / f"batch_params_2026_W{hours}_{arm}_seed{seed}.xml"
                write_params(p, f"WINDOW ARM {arm} at simulationHours={hours}, "
                                f"seed {seed} (dose decomposition by window)",
                             "D1 window arms", seed, hours, code)
                n += 1
    print(f"wrote {n} batch params files")


if __name__ == "__main__":
    build_sweep_csvs()
    build_params()
